### ISSUE TITLE
Please release :)

### ISSUE THREAD

**Issue by ronkorving** [fitzgen/glob-to-regexp#18]
Now that the correct SPDX identifier has been set in package.json, thanks to https://github.com/fitzgen/glob-to-regexp/commit/dd7b8a061b986098d67fed9cc93fc015771b4741 it would be nice if that could be released on NPM. It would help (at least me) with license validation automation.

Thanks!

**Comment by fitzgen** [comment]
Published 0.4.1

**Comment by ronkorving** [comment]
Thanks!
